Add StreamingFileUploadRequest
micronaut-projects/micronaut-object-storage pull request #424
Opened 2024-02-19 11:54 UTC by johanra

This PR contributes contains an implementation of StreamingFileUploadRequest and at the same time fixes #423 where the Azure implementation is calling getInputStream of the StreamingFileUploadRequest twice

2024-02-19 11:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/micronaut-projects/micronaut-object-storage?pullRequest=424) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/micronaut-projects/micronaut-object-storage?pullRequest=424) before we can accept your contribution.<br/><hr/>**johanraedemaeker** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/micronaut-projects/micronaut-object-storage?pullRequest=424) it.</sub>

2024-03-27 07:16 UTC, sdelamo commented
Thanks @johanra Can you sign the CLA?

2024-03-28 09:03 UTC, johanra commented
@sdelamo  CLA is signed now

2024-03-28 14:25 UTC, sdelamo requested changes

2024-03-28 14:25 UTC, sdelamo commented on object-storage-core/src/main/java/io/micronaut/objectstorage/request/UploadRequest.java
> +    static UploadRequest fromStreamingFileUpload(@NonNull StreamingFileUpload streamingFileUpload) {
add `@since` to javadoc

2024-03-28 14:25 UTC, sdelamo commented on object-storage-core/src/main/java/io/micronaut/objectstorage/request/UploadRequest.java
> +    @NonNull
add `@since` to javadoc

2024-03-28 14:25 UTC, sdelamo commented on object-storage-core/src/main/java/io/micronaut/objectstorage/request/StreamingFileUploadRequest.java
> +public class StreamingFileUploadRequest implements UploadRequest {
add `@since` to javadoc

2024-04-02 09:58 UTC, yawkat approved these changes

2024-04-11 07:20 UTC, marcinfigiel commented
Hi Guys,
Wouldn't it make sense to extend this PR to allow streaming uploads to other cloud providers too? Right now it adds the abstraction, but implementation is limited to Azure only.

2024-04-29 19:55 UTC, scprek commented
> Hi Guys, Wouldn't it make sense to extend this PR to allow streaming uploads to other cloud providers too? Right now it adds the abstraction, but implementation is limited to Azure only.

I have the same question, specifically so we can use with AWS

2024-06-06 11:48 UTC, marcinfigiel commented
What is the current status of this topic? Has it stalled?

2024-10-25 10:14 UTC, wgruszczyk commented
Hi!
Any chance to close this ticket any time soon? We're waiting for the feature and need to make a decision to either wait or workaround this limitation.

2024-11-12 11:21 UTC, sdelamo commented on object-storage-core/src/main/java/io/micronaut/objectstorage/request/StreamingFileUploadRequest.java
> + * An {@link UploadRequest} backed by a {@link StreamingFileUpload}.
```suggestion
 * An {@link UploadRequest} backed by a {@link StreamingFileUpload}.
 * @since 2.7.0
```

2024-11-12 11:21 UTC, sdelamo commented on object-storage-core/src/main/java/io/micronaut/objectstorage/request/UploadRequest.java
> +     * @return An {@link UploadRequest} from the given {@link StreamingFileUpload}.
```suggestion
     * @return An {@link UploadRequest} from the given {@link StreamingFileUpload}.
     * @since 2.7.0
```

2024-11-12 11:21 UTC, sdelamo commented on object-storage-core/src/main/java/io/micronaut/objectstorage/request/UploadRequest.java
> +     * @return An {@link UploadRequest} from the given {@link StreamingFileUpload} and key.
```suggestion
     * @return An {@link UploadRequest} from the given {@link StreamingFileUpload} and key.
     * @since 2.7.0
```

2024-11-12 11:48 UTC, merged

2024-11-12 11:49 UTC, sdelamo commented
@johanra Thanks for the contribution 
@wgruszczyk @marcinfigiel @scprek I am going to merge this and it will be part of 4.7.0. We can add support to other cloud vendors later.